name: Build LaTeX document
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@2.5.0
        with:
          root_file: main.tex
          
      - name: Copy PDF
        run: mkdir publish && cp main.pdf publish/Schnelleinstieg.pdf
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: publish
      
      - name: Get tag for Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: publish/Schnelleinstieg.pdf
          draft: false
          prerelease: false
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
